# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0036_ensure_anon_user_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='nlu_api_config',
            field=models.TextField(help_text='Settings for Natural Language Understand API', max_length=255, null=True, verbose_name='NLU API Configuration'),
        ),
    ]
