# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_auto_20171124_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='nlu_api_config',
            field=models.TextField(help_text='Settings for Natural Language Understand API', null=True, verbose_name='NLU API Configuration'),
        ),
    ]
