# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_auto_20171124_1609'),
        ('orgs', '0037_org_nlu_api_config'),
    ]

    operations = [
    ]
