# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-04 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0161_auto_20180528_1833")]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="ignore_triggers",
            field=models.BooleanField(default=False, help_text="Ignore keyword and NLU triggers while in this flow"),
        )
    ]
